version: '3.8'
services:
  # Define the Rails application service
  rails-app:
    env_file:
      - .env
    # Build the Docker image for the Rails app
    build:
      context: .  # Specify the build context directory
      dockerfile: Dockerfile  # Specify the Dockerfile to use for building the image
    ports:
      - "3001:3001"  # Map port 3001 on the host to port 3001 in the container
    restart: unless-stopped  # Restart the container unless it is explicitly stopped
    volumes:
      - .:/rails  # Mount the host directory to the container's /rails directory
      - db_data:/rails/storage

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /volume1/docker/data
      o: bind
