services:
  # Define the Rails application service
  app:
    image: 192.168.178.35:5005/kiosk:latest
    env_file:
      - .env
    ports:
      - "3001:3001"  # Map port 3001 on the host to port 3001 in the container
    restart: unless-stopped  # Restart the container unless it is explicitly stopped
    volumes:
      - .:/rails  # Mount the host directory to the container's /rails directory
